<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-07-26 17:18
return array(
	'tx_sessionpassword_helper_sessionhelper' => t3lib_extMgm::extPath('sessionpassword', 'Classes/Helper/SessionHelper.php'),
	'tx_sessionpassword_service_contentobjectservice' => t3lib_extMgm::extPath('sessionpassword', 'Classes/Service/ContentObjectService.php'),
	'tx_sessionpassword_service_frontendusergroupservice' => t3lib_extMgm::extPath('sessionpassword', 'Classes/Service/FrontendUsergroupService.php')
);
