services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Sessionpassword\:
    resource: '../Classes/*'
    exclude: '../Classes/Helper/SessionHelper.php'

  B13\Sessionpassword\EventListener\ModifyResolvedFrontendGroups:
    tags:
      - name: event.listener
        identifier: 'txSessionPasswordGroups'
